[package]
name = "adder1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adder_lib = { path = "../adder_lib"}  #adder1 依赖adder_lib
rand = "0.3.15"